import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { LayoutDashboard, Package, ShoppingBag, AlertTriangle, Search, Plus, Wine, RefreshCw, ShoppingCart, CheckCircle, Trash2 } from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';
const USER = import.meta.env.VITE_DEMO_USER_ID || '';
async function api(path, options = {}) { const r = await fetch(`${API}${path}`, { headers: { 'Content-Type': 'application/json' }, ...options }); if (!r.ok) throw Error((await r.json().catch(() => ({}))).detail || 'Request failed'); return r.status === 204 ? null : r.json(); }

function AdminApp() {
  const [page, setPage] = useState('dashboard'), [products, setProducts] = useState([]), [summary, setSummary] = useState({}), [query, setQuery] = useState(''), [cart, setCart] = useState({ items: [], total: 0 }), [notice, setNotice] = useState('');
  const load = async () => { try { setProducts(await api(`/api/products?search=${encodeURIComponent(query)}`)); setSummary(await api('/api/dashboard/summary')); } catch (e) { setNotice(e.message); } };
  useEffect(() => { load(); }, []);
  const add = async p => { if (!USER) return setNotice('Set VITE_DEMO_USER_ID to enable cart and checkout.'); try { setCart(await api(`/api/cart/${USER}/items`, { method: 'POST', body: JSON.stringify({ product_id: p.id, quantity: 1 }) })); setNotice(`${p.name} added to cart`); } catch (e) { setNotice(e.message); } };
  const openCart = async () => { if (USER) setCart(await api(`/api/cart/${USER}`)); setPage('cart'); };
  const update = async p => { const value = prompt(`New stock for ${p.name}`, p.stock_quantity); if (value !== null) { await api(`/api/inventory/${p.id}`, { method: 'PATCH', body: JSON.stringify({ stock_quantity: Number(value) }) }); load(); } };
  return <div className="app"><aside><div className="brand"><Wine size={20}/> bottle<span>shop</span></div><nav><Nav active={page === 'dashboard'} icon={<LayoutDashboard/>} label="Overview" click={() => setPage('dashboard')}/><Nav active={page === 'catalogue'} icon={<ShoppingBag/>} label="Shop catalogue" click={() => setPage('catalogue')}/><Nav active={page === 'inventory'} icon={<Package/>} label="Inventory" click={() => setPage('inventory')}/><Nav active={page === 'orders'} icon={<ShoppingBag/>} label="Orders" click={() => setPage('orders')}/></nav><div className="aside-foot">Local workspace<br/><small>Supabase + FastAPI</small></div></aside><main><header><div><p className="eyebrow">BOTTLESHOP / {page.toUpperCase()}</p><h1>{page === 'catalogue' ? 'Shop catalogue' : page === 'inventory' ? 'Inventory' : page === 'orders' ? 'Orders' : 'Good morning, Admin'}</h1><p className="muted">Manage bottles, stock and customer orders.</p></div><button className="cart-button" onClick={openCart}><ShoppingCart size={17}/> Cart</button></header>{notice && <div className="notice">{notice}<button onClick={() => setNotice('')}>×</button></div>}{page === 'dashboard' && <><section className="stats"><Stat label="Active products" value={summary.products} icon={<Package/>}/><Stat label="Units in stock" value={summary.units} icon={<ShoppingBag/>}/><Stat label="Low stock items" value={summary.low_stock} icon={<AlertTriangle/>} warning/></section><Inventory products={products} update={update} reload={load}/></>}{page === 'inventory' && <Inventory products={products} update={update} reload={load}/>} {page === 'catalogue' && <><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search products or brands" value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === 'Enter' && load()}/></div></div><div className="catalogue">{products.map(p => <ProductCard key={p.id} product={p} add={() => add(p)}/>)}</div></>}{page === 'cart' && <Cart cart={cart} refresh={openCart} checkout={() => setPage('checkout')}/>} {page === 'checkout' && <Checkout total={cart.total} done={() => { setCart({ items: [], total: 0 }); setPage('orders'); }}/>} {page === 'orders' && <Orders/>}</main></div>;
}
function Nav({ active, icon, label, click }) { return <a className={active ? 'active' : ''} onClick={click}>{icon}{label}</a>; }
function Stat({ label, value, icon, warning }) { return <div className="stat"><div className={warning ? 'stat-icon warning' : 'stat-icon'}>{icon}</div><div><p>{label}</p><h2>{value ?? '—'}</h2></div></div>; }
function Inventory({ products, update, reload }) { return <section className="panel"><div className="panel-head"><div><h2>Product inventory</h2><p className="muted">Manage availability and stock levels</p></div><button className="icon-btn" onClick={reload}><RefreshCw size={16}/></button></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th/></tr></thead><tbody>{products.map(p => <tr key={p.id}><td><div className="product"><div className="bottle"><Wine size={19}/></div><div><strong>{p.name}</strong><small>{p.brand} · {p.volume_ml}ml · {p.alcohol_percentage}% ABV</small></div></div></td><td>{p.category || 'Uncategorised'}</td><td>₹{Number(p.price).toLocaleString('en-IN')}</td><td><strong>{p.stock_quantity}</strong><small>/ reorder {p.reorder_level}</small></td><td><span className={`badge ${p.stock_quantity <= p.reorder_level ? 'warning' : 'success'}`}>{p.stock_quantity <= p.reorder_level ? 'Low stock' : 'In stock'}</span></td><td><button className="link" onClick={() => update(p)}>Update</button></td></tr>)}</tbody></table></div></section>; }
function ProductCard({ product, add }) { return <article className="product-card"><div className="product-art"><Wine size={50}/></div><p className="eyebrow">{product.category || 'SPIRITS'}</p><h3>{product.name}</h3><p className="muted">{product.brand} · {product.volume_ml}ml</p><div className="card-bottom"><strong>₹{Number(product.price).toLocaleString('en-IN')}</strong><button className="small-primary" onClick={add}><Plus size={15}/> Add</button></div></article>; }
function Cart({ cart, refresh, checkout }) { return <section className="panel narrow"><h2>Your cart</h2>{!cart.items.length ? <div className="empty">Your cart is empty.</div> : <><div className="cart-list">{cart.items.map(i => <div className="cart-row" key={i.id}><div><strong>{i.name}</strong><small>₹{i.price} × {i.quantity}</small></div><strong>₹{Number(i.line_total).toLocaleString('en-IN')}</strong><button className="icon-btn" onClick={async () => { await api(`/api/cart/items/${i.id}`, { method: 'DELETE' }); refresh(); }}><Trash2 size={15}/></button></div>)}</div><div className="cart-total"><span>Total</span><strong>₹{Number(cart.total).toLocaleString('en-IN')}</strong></div><button className="primary full" onClick={checkout}>Continue to checkout</button></>}</section>; }
function Checkout({ total, done }) { const [address, setAddress] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false); const submit = async e => { e.preventDefault(); if (!USER) return setError('Set VITE_DEMO_USER_ID before checkout.'); setBusy(true); setError(''); try { await api('/api/orders', { method: 'POST', body: JSON.stringify({ user_id: USER, delivery_address: address }) }); done(); } catch (e) { setError(e.message); } finally { setBusy(false); } }; return <section className="panel narrow"><h2>Checkout</h2><p className="muted">Total: ₹{Number(total).toLocaleString('en-IN')}</p>{error && <div className="notice">{error}</div>}<form onSubmit={submit}><label>Delivery address<textarea required value={address} onChange={e => setAddress(e.target.value)} /></label><button className="primary full" disabled={busy}><CheckCircle size={16}/> {busy ? 'Placing order…' : 'Place order'}</button></form></section>; }
function Orders() { const [orders, setOrders] = useState([]); useEffect(() => { if (USER) api(`/api/orders?user_id=${USER}`).then(setOrders).catch(() => {}); }, []); return <section className="panel"><h2>Orders</h2><p className="muted">Recent customer orders</p>{orders.length ? orders.map(o => <div className="order-row" key={o.id}><div><strong>#{o.id.slice(0, 8)}</strong><small>{o.delivery_address}</small></div><span className="badge success">{o.status}</span><strong>₹{Number(o.total_amount).toLocaleString('en-IN')}</strong></div>) : <div className="empty">No orders yet.</div>}</section>; }
function Storefront() {
  const [products, setProducts] = useState([]), [cart, setCart] = useState([]), [auth, setAuth] = useState(false), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [message, setMessage] = useState('');
  useEffect(() => { api('/api/products').then(setProducts).catch(e => setMessage(e.message)); }, []);
  const login = async e => { e.preventDefault(); try { const r = await api('/api/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); localStorage.setItem('access_token', r.access_token); setAuth(true); setMessage('Signed in successfully'); } catch (e) { setMessage(e.message); } };
  const checkout = async () => { if (!auth) return setMessage('Please sign in before checkout.'); setMessage('Checkout is ready.'); };
  return <div className="app"><main style={{marginLeft: 0, width: '100%'}}><header><div><p className="eyebrow">BOTTLESHOP / STORE</p><h1>Discover your next bottle</h1><p className="muted">Browse our catalogue. Sign in only when you are ready to order.</p></div><button className="cart-button" onClick={checkout}>Cart ({cart.length})</button></header>{message && <div className="notice">{message}</div>}<section className="catalogue">{products.map(p => <ProductCard key={p.id} product={p} add={() => { setCart([...cart, p]); setMessage(`${p.name} added to cart`); }}/>)}</section><section className="panel narrow"><h2>Customer sign in</h2><form onSubmit={login}><label>Email<input type="email" required value={email} onChange={e => setEmail(e.target.value)}/></label><label>Password<input type="password" required value={password} onChange={e => setPassword(e.target.value)}/></label><button className="primary full">Sign in to order</button></form><p className="muted">Admin? <a href="/admin">Open admin dashboard</a></p></section></main></div>;
}

function App() {
  return window.location.pathname.startsWith('/admin') ? <AdminApp/> : <Storefront/>;
}

createRoot(document.getElementById('root')).render(<App/>);
